### ISSUE TITLE
How to run it locally?

### ISSUE THREAD

**Issue by edarin** [coopcycle/coopcycle-docs#17]
The readme is incomplete. cf `gem` stands for ruby ? do i need to install ruby? I'll complete the readme when I'll have a clearer idea :)

**Comment by alexsegura** [comment]
Yes, [RubyGems](https://rubygems.org/?locale=fr) (the `gem` command) is the de-facto [package manager for Ruby](https://www.ruby-lang.org/fr/libraries/)

When you install Ruby, RubyGems is installed too
