### ISSUE TITLE
Start glossary page

### ISSUE THREAD

**Issue by Atala** [coopcycle/coopcycle-docs#85]

**Comment by Paul-Eraman-CoopCycle** [comment]
we did!

**Comment by Paul-Eraman-CoopCycle** [comment]
maybe we should link to it here...

**Comment by Atala** [comment]
still in google drive at the moment [https://docs.google.com/document/d/1UpPPEWqnOBceNlql5Sisr7UUTESoKK3mpLxf2HivIFk/edit#heading=h.1bzq13sezh4l](https://docs.google.com/document/d/1UpPPEWqnOBceNlql5Sisr7UUTESoKK3mpLxf2HivIFk/edit#heading=h.1bzq13sezh4l)

maybe create an epic to reorganize documentation?

**Comment by Paul-Eraman-CoopCycle** [comment]
yeah, ill make that now
